Drzn.Test/Areas/Car/Controllers/CarBrandsController.cs
using Drzn.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Drzn.Test.Areas.Car.Controllers
{
    public class CarBrandsController : Controller
    {
        // GET: Car/CarBrands
        public ActionResult Index()
        {
            var context = DataContext.JoinOrCreate();

            var brands = context.CarBrands.ToList();

            return View(brands);
        }
    }
}

Drzn.Test/Areas/Car/Controllers/CarPartsController.cs
using Drzn.Test.Areas.Car.Models;
using Drzn.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Drzn.Test.Areas.Car.Controllers
{
    public class CarPartsController : Controller
    {
        public ActionResult Index()
        {
            var context = DataContext.JoinOrCreate();
            var parts = context.CarParts.ToList();

            return View(parts);
        }

        public ActionResult Search(string term)
        {
            var context = DataContext.JoinOrCreate();

            var parts = context.CarParts.Where(x => x.Title.Contains(term) || x.Brand.Title.Contains(term))
                .ToList()
                .Select(x => x.FullTitle);

            return Json(parts, JsonRequestBehavior.AllowGet);
        }
    }
}

Drzn.Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@RenderSection("PageTitle")</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Запчасти", "Index", "CarParts", new { area = "Car" }, null)</li>
                    <li>@Html.ActionLink("Марки", "Index", "CarBrands", new { area = "Car" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("Body", false)
</body>
</html>